/**
 * 
 */
package trading.elements;

/**
 * Technical analysis (TA) event. Generated by calculating various TA values by
 * appropriate broker/data supplier library
 */
public interface ITAEvent {

	public boolean isLong();

	public boolean isOnMarket();

	public double getSTPPrice();

	public double getLMTPrice();

	public double getStopLossPrice();

	public long getTime();

	public String getName();

	public void roundSL(int pipScale);

}
